-- ============================================================
-- SEED: Nonprofit Members
-- AUTO-GENERATED by scripts/generate-nonprofit-seed.ts
-- Source: src/shared/data/nonprofitDemoData.ts
-- Safe to re-run (idempotent upserts on fixed seed UUIDs).
-- Prerequisite: at least one row in auth.users
-- ============================================================

-- Abort if no auth users (created_by subquery would be NULL)
DO $$
BEGIN
  IF (SELECT COUNT(*) FROM auth.users) = 0 THEN
    RAISE EXCEPTION 'SEED ABORTED: No users in auth.users. Sign up via the app first.';
  END IF;
END $$;


DELETE FROM public.nonprofit_members WHERE id IN ('cd5baeb7-51de-4a6a-804e-73849fc39cc5', 'ee5072d8-ad48-4017-8011-d9f87d0ca7bd', '751f1ab1-0012-4c82-870b-ec4684c4ec81', 'e5a156bd-caf0-420f-8b7f-4887a687dcf5', 'a1c27546-bb52-4b44-8eec-6e45d5f0f355', 'c2a6006c-df3a-4d0f-8853-f47e2bc35a26', '2b4d3be0-cdf2-42fc-8f35-ce8b961be1a1', '52933304-fd68-4be6-805d-81408a0210c8', '293247d2-5075-479a-8b4d-903a1b27138f', '08559d32-bac2-4260-8794-178478c422d1', '372acd84-48e3-4650-8122-0ab400b45248', 'a2d62b39-b4b0-402b-892b-d4d354fe300c', 'e2b3dc74-8a20-44b9-895d-a2b2f06e8365', 'd4d24225-e6af-4f19-8fa4-479b05984323', '4ab9015a-fad7-458c-82b1-2bb14d0ce9ba', '23d6c6a7-d8a2-4af9-8a00-20f8fd411e33', 'e31b8e43-0096-4b9b-8bd5-a3f5a009697f', '3995ab96-3f37-40b2-8eae-2a055ffa0171', '5b9286e5-ed11-4cb8-8e52-07222c7ba858', '2e484e13-2db1-4df4-8cc2-a29f146f0b22');

INSERT INTO public.nonprofit_members (
  id, created_by, name, email, phone, tier, status, join_date, renewal_date, employer, interests
) VALUES
  ('cd5baeb7-51de-4a6a-804e-73849fc39cc5', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Angela Torres', 'angela.torres@email.com', '(617) 555-0101', 'General', 'Active', '2024-06-17', '2026-12-14', 'Boston Public Schools', ARRAY['Youth Programs', 'Education', 'Mentorship']),
  ('ee5072d8-ad48-4017-8011-d9f87d0ca7bd', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Marcus Webb', 'marcus.webb@email.com', NULL, 'General', 'Active', '2024-12-24', '2027-01-13', 'Webb Construction', ARRAY['Community Development', 'Workforce']),
  ('751f1ab1-0012-4c82-870b-ec4684c4ec81', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Sandra Osei', 'sandra.osei@email.com', '(617) 555-0103', 'General', 'Active', '2025-05-13', '2026-09-20', NULL, ARRAY['Health', 'Family Services']),
  ('e5a156bd-caf0-420f-8b7f-4887a687dcf5', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Daniel Flores', 'd.flores@email.com', NULL, 'General', 'Active', '2025-08-21', '2026-08-21', 'Flores Media', ARRAY['Communications', 'Fundraising']),
  ('a1c27546-bb52-4b44-8eec-6e45d5f0f355', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Nadia Okafor', 'nadia.okafor@email.com', '(617) 555-0105', 'General', 'Expiring', '2025-06-27', '2026-06-27', NULL, ARRAY['Digital Literacy', 'Youth']),
  ('c2a6006c-df3a-4d0f-8853-f47e2bc35a26', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Chris Bailey', 'c.bailey@email.com', NULL, 'General', 'Expiring', '2025-06-22', '2026-06-22', NULL, ARRAY['Environment', 'Community Garden']),
  ('2b4d3be0-cdf2-42fc-8f35-ce8b961be1a1', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Yuki Tanaka', 'yuki.tanaka@email.com', NULL, 'General', 'Lapsed', '2025-05-13', '2026-05-13', 'Tanaka Design', ARRAY['Arts', 'Culture']),
  ('52933304-fd68-4be6-805d-81408a0210c8', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Omar Hassan', 'omar.hassan@email.com', '(617) 555-0108', 'General', 'Lapsed', '2025-02-02', '2026-04-18', NULL, ARRAY['Advocacy', 'Policy']),
  ('293247d2-5075-479a-8b4d-903a1b27138f', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Emily Saunders', 'emily.s@email.com', NULL, 'General', 'Pending', '2026-06-10', '2027-06-10', 'Saunders Consulting', ARRAY['Nonprofit Strategy', 'Governance']),
  ('08559d32-bac2-4260-8794-178478c422d1', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Dr. Alicia Ramos', 'a.ramos@healthpartners.org', '(617) 555-0110', 'Professional', 'Active', '2024-06-27', '2027-02-17', 'Health Partners Network', ARRAY['Public Health', 'Research', 'Grants']),
  ('372acd84-48e3-4650-8122-0ab400b45248', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Kevin Park', 'kevin.park@kpmg.com', NULL, 'Professional', 'Active', '2024-10-25', '2026-10-15', 'KPMG', ARRAY['Finance', 'Nonprofit Auditing']),
  ('a2d62b39-b4b0-402b-892b-d4d354fe300c', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Jennifer Walsh', 'j.walsh@lawfirm.com', '(617) 555-0112', 'Professional', 'Active', '2025-03-24', '2027-03-19', 'Walsh & Associates', ARRAY['Legal Aid', 'Pro Bono']),
  ('e2b3dc74-8a20-44b9-895d-a2b2f06e8365', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Thomas Rivera', 't.rivera@email.com', NULL, 'Professional', 'Expiring', '2025-06-20', '2026-06-20', 'Rivera Financial', ARRAY['Wealth Management', 'Philanthropy']),
  ('d4d24225-e6af-4f19-8fa4-479b05984323', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Priya Mehta', 'priya.mehta@tech.com', NULL, 'Professional', 'Expiring', '2025-07-02', '2026-07-02', 'TechBridge Solutions', ARRAY['Technology', 'Digital Inclusion']),
  ('4ab9015a-fad7-458c-82b1-2bb14d0ce9ba', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Carlos Diaz', 'carlos.diaz@email.com', '(617) 555-0115', 'Professional', 'Lapsed', '2025-02-22', '2026-05-03', NULL, ARRAY['Real Estate', 'Community Housing']),
  ('23d6c6a7-d8a2-4af9-8a00-20f8fd411e33', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Patricia Lee', 'p.lee@brightsideboard.org', '(617) 555-0116', 'Board', 'Active', '2023-03-05', '2027-06-17', 'Lee Foundation', ARRAY['Governance', 'Strategic Planning', 'Major Gifts']),
  ('e31b8e43-0096-4b9b-8bd5-a3f5a009697f', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Robert Kim', 'r.kim@brightsideboard.org', NULL, 'Board', 'Active', '2023-12-30', '2027-04-13', 'Kim Enterprises', ARRAY['Finance', 'Operations', 'Audit']),
  ('3995ab96-3f37-40b2-8eae-2a055ffa0171', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Sarah Mitchell', 's.mitchell@brightsideboard.org', '(617) 555-0118', 'Board', 'Active', '2022-05-09', '2026-12-14', 'Mitchell Group', ARRAY['Fundraising', 'Communications', 'Events']),
  ('5b9286e5-ed11-4cb8-8e52-07222c7ba858', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Mayor Gloria Chen', 'g.chen@boston.gov', NULL, 'Honorary', 'Active', '2024-04-08', '2027-06-17', 'City of Boston', ARRAY['Community Development', 'Policy']),
  ('2e484e13-2db1-4df4-8cc2-a29f146f0b22', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Dr. James Wright', 'j.wright@university.edu', NULL, 'Honorary', 'Active', '2023-09-21', '2027-06-17', 'Northeastern University', ARRAY['Research', 'Education', 'Youth'])
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  tier = EXCLUDED.tier,
  status = EXCLUDED.status,
  join_date = EXCLUDED.join_date,
  renewal_date = EXCLUDED.renewal_date,
  employer = EXCLUDED.employer,
  interests = EXCLUDED.interests,
  updated_at = now();
