-- ============================================================
-- SEED: Nonprofit Volunteers + Shifts
-- AUTO-GENERATED by scripts/generate-nonprofit-seed.ts
-- Source: src/shared/data/nonprofitDemoData.ts
-- Safe to re-run (idempotent upserts on fixed seed UUIDs).
-- Prerequisite: at least one row in auth.users
-- ============================================================

-- Abort if no auth users (created_by subquery would be NULL)
DO $$
BEGIN
  IF (SELECT COUNT(*) FROM auth.users) = 0 THEN
    RAISE EXCEPTION 'SEED ABORTED: No users in auth.users. Sign up via the app first.';
  END IF;
END $$;


DELETE FROM public.nonprofit_volunteer_shifts WHERE id IN ('e0956fb7-fdec-4c20-8ff2-23bd1e4be6e2', '1b86ee90-0a7e-4eea-86f1-8442273db46e', '5ff7759f-db02-4ced-851b-340ceeb908aa', 'c5685f3a-f719-4879-8778-9ec9b39dd4c6', '5b442746-e1c6-4d01-8195-4fd2c3a05fde', 'c4b5ef29-9766-4f72-891c-9065f59fbe61', 'b04e98cc-9494-4a5d-8918-6253ee968223', '98373416-0e3b-48a3-8b71-ec0acdc34c1d', '12a7f818-d041-4d5d-834a-639d323cf872', '5854cb7a-78b6-48ca-8dbf-d74a9555924d', 'b2ac79d2-3d60-48ff-8e05-e0151df63d57', '7eb9c8d3-17b1-4f24-8b89-c5418a411c0e', '3e44225c-dc0b-4cf7-89f3-0316facf7ec6', '691f0cd0-3ce1-49f5-8585-be6c491c71a3', 'dfd7ca8c-f370-4350-8dc8-628e7a3a43e4', '76ee65a5-3d3e-47db-84b9-af97a20c4e35', 'a0249466-a49f-46a6-8758-df9b7f0f76f4', 'd9aba5ff-862e-4da3-810d-9d4659157f97', '00f3eda4-9d34-4e4b-8122-d432d3da10d7', '6a3f1eba-1abb-4596-8636-ad49aa77789a', 'ee3787d1-3039-4253-8a4b-f8f661fd75d7', '5181c4f2-bfe2-4bbd-8bc7-c8842742645e', 'd55f2e99-b0dd-4e95-884c-d460c5e42c00', '2242033d-97cd-4d9e-860f-cade0ed69eb4', '4d5358bf-8145-45da-8614-b98d19fdc12a', 'ab510d75-0a6f-4b7e-835e-0cf57c3c4a31', 'd039170d-a76c-4f29-8c26-85d3046e513f', '969d18e6-019b-47b4-8a34-09d7ffe45e8e', 'be25a357-ed80-4b9b-89de-1aa772031402', '980d8d28-bc53-41f4-8357-f2953808ecc8');
DELETE FROM public.nonprofit_volunteers WHERE id IN ('8bef06fd-cd96-4ce9-8bab-23332204b6f0', 'cebbdf24-0cdf-47dc-8f42-6f2ac1f466ce', '0e119d63-378c-466e-869e-b9b932195e9a', '1826d7a2-a053-4ecd-8fe6-ef3a71b9b0e5', '136376f8-638a-4135-89f8-85d6d2df6dbd', '7d3cbdc3-ae45-451e-86c5-bb70ef964beb', '839142b6-25db-492b-8fde-0550dda637ef', '3f86f7e3-7b44-4924-8956-b1fe553f1125', '34e1d7b6-a602-4474-8c51-da205c1e544d', '860e7db7-163e-4dad-8fcc-f0d51f11c740', '48f965a9-9ac2-4827-8fef-2c898dcd1001', '08930422-421a-4b64-8e11-61b7dfda4ceb', '04dbeb0e-00b8-497f-8040-d3171d144a8d', '3b9ef0a9-c7ec-41bd-8afc-0d61deaf9272', '21609218-a3b9-48d3-8fd4-e2641234b1df');

INSERT INTO public.nonprofit_volunteers (
  id, created_by, name, email, phone, skills, availability, total_hours, joined_date, is_also_donor, donor_total_giving
) VALUES
  ('8bef06fd-cd96-4ce9-8bab-23332204b6f0', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Angela Torres', 'angela.torres@email.com', NULL, ARRAY['Youth Mentoring', 'Administrative'], ARRAY['Weekday Afternoons', 'Weekends'], 312, '2024-06-27', TRUE, 4800),
  ('cebbdf24-0cdf-47dc-8f42-6f2ac1f466ce', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Marcus Webb', 'marcus.webb@email.com', NULL, ARRAY['Event Setup', 'Fundraising', 'Photography'], ARRAY['Weekends', 'Flexible'], 185, '2024-12-24', FALSE, NULL),
  ('0e119d63-378c-466e-869e-b9b932195e9a', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Nadia Okafor', 'nadia.okafor@email.com', NULL, ARRAY['Digital Skills', 'Translation'], ARRAY['Evenings', 'Weekends'], 98, '2025-08-21', TRUE, 1200),
  ('1826d7a2-a053-4ecd-8fe6-ef3a71b9b0e5', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Daniel Flores', 'd.flores@email.com', NULL, ARRAY['Photography', 'Event Setup', 'Fundraising'], ARRAY['Weekends', 'Flexible'], 240, '2025-05-13', FALSE, NULL),
  ('136376f8-638a-4135-89f8-85d6d2df6dbd', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Lisa Chen', 'lisa.chen@email.com', NULL, ARRAY['Health Screening', 'Administrative'], ARRAY['Weekday Mornings', 'Weekday Afternoons'], 420, '2023-12-30', TRUE, 8500),
  ('7d3cbdc3-ae45-451e-86c5-bb70ef964beb', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'David Osei', 'david.osei@email.com', NULL, ARRAY['Food Distribution', 'Event Setup'], ARRAY['Weekends'], 156, '2025-02-02', TRUE, 2400),
  ('839142b6-25db-492b-8fde-0550dda637ef', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Carol Nguyen', 'carol.nguyen@email.com', NULL, ARRAY['Administrative', 'Translation', 'Digital Skills'], ARRAY['Weekday Mornings', 'Evenings'], 287, '2024-09-05', FALSE, NULL),
  ('3f86f7e3-7b44-4924-8956-b1fe553f1125', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'James Wright Jr.', 'j.wright.jr@email.com', NULL, ARRAY['Legal', 'Administrative'], ARRAY['Flexible'], 72, '2025-12-19', FALSE, NULL),
  ('34e1d7b6-a602-4474-8c51-da205c1e544d', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Aisha Patel', 'aisha.patel@email.com', NULL, ARRAY['Youth Mentoring', 'Digital Skills', 'Photography'], ARRAY['Weekday Afternoons', 'Weekends'], 345, '2024-06-17', TRUE, 3600),
  ('860e7db7-163e-4dad-8fcc-f0d51f11c740', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Robert Santos', 'r.santos@email.com', NULL, ARRAY['Food Distribution', 'Event Setup', 'Fundraising'], ARRAY['Weekends', 'Evenings'], 201, '2025-04-23', FALSE, NULL),
  ('48f965a9-9ac2-4827-8fef-2c898dcd1001', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Michelle Kim', 'michelle.kim@email.com', NULL, ARRAY['Health Screening', 'Translation'], ARRAY['Weekday Mornings'], 118, '2025-09-30', FALSE, NULL),
  ('08930422-421a-4b64-8e11-61b7dfda4ceb', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Steven Park', 's.park@email.com', NULL, ARRAY['Administrative', 'Fundraising'], ARRAY['Evenings', 'Weekends'], 89, '2026-01-18', TRUE, 950),
  ('04dbeb0e-00b8-497f-8040-d3171d144a8d', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Fatima Hassan', 'fatima.hassan@email.com', NULL, ARRAY['Translation', 'Food Distribution', 'Youth Mentoring'], ARRAY['Weekday Afternoons', 'Weekends'], 263, '2024-10-25', FALSE, NULL),
  ('3b9ef0a9-c7ec-41bd-8afc-0d61deaf9272', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Brian O''Connor', 'b.oconnor@email.com', NULL, ARRAY['Event Setup', 'Photography'], ARRAY['Weekends', 'Flexible'], 134, '2025-06-02', FALSE, NULL),
  ('21609218-a3b9-48d3-8fd4-e2641234b1df', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Jasmine Rivera', 'jasmine.rivera@email.com', NULL, ARRAY['Youth Mentoring', 'Administrative', 'Digital Skills'], ARRAY['Weekday Afternoons', 'Evenings'], 200, '2025-03-24', FALSE, NULL)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  skills = EXCLUDED.skills,
  availability = EXCLUDED.availability,
  total_hours = EXCLUDED.total_hours,
  joined_date = EXCLUDED.joined_date,
  is_also_donor = EXCLUDED.is_also_donor,
  donor_total_giving = EXCLUDED.donor_total_giving,
  updated_at = now();

INSERT INTO public.nonprofit_volunteer_shifts (
  id, volunteer_id, event_name, date, hours, status
) VALUES
  ('e0956fb7-fdec-4c20-8ff2-23bd1e4be6e2', '8bef06fd-cd96-4ce9-8bab-23332204b6f0', 'Spring Gala Setup', '2026-06-12', 4, 'Completed'),
  ('1b86ee90-0a7e-4eea-86f1-8442273db46e', '8bef06fd-cd96-4ce9-8bab-23332204b6f0', 'Youth Mentorship Session', '2026-06-24', 2, 'Upcoming'),
  ('5ff7759f-db02-4ced-851b-340ceeb908aa', 'cebbdf24-0cdf-47dc-8f42-6f2ac1f466ce', 'Community Health Fair', '2026-05-27', 6, 'Completed'),
  ('c5685f3a-f719-4879-8778-9ec9b39dd4c6', 'cebbdf24-0cdf-47dc-8f42-6f2ac1f466ce', 'Summer Leadership Summit', '2026-08-01', 8, 'Upcoming'),
  ('5b442746-e1c6-4d01-8195-4fd2c3a05fde', '0e119d63-378c-466e-869e-b9b932195e9a', 'Tech Training Workshop', '2026-06-03', 3, 'Completed'),
  ('c4b5ef29-9766-4f72-891c-9065f59fbe61', '0e119d63-378c-466e-869e-b9b932195e9a', 'Community Dinner', '2026-06-29', 4, 'Upcoming'),
  ('b04e98cc-9494-4a5d-8918-6253ee968223', '1826d7a2-a053-4ecd-8fe6-ef3a71b9b0e5', 'Spring Gala', '2026-06-12', 6, 'Completed'),
  ('98373416-0e3b-48a3-8b71-ec0acdc34c1d', '1826d7a2-a053-4ecd-8fe6-ef3a71b9b0e5', 'Summer Leadership Summit', '2026-08-01', 8, 'Upcoming'),
  ('12a7f818-d041-4d5d-834a-639d323cf872', '136376f8-638a-4135-89f8-85d6d2df6dbd', 'Community Health Fair', '2026-05-27', 8, 'Completed'),
  ('5854cb7a-78b6-48ca-8dbf-d74a9555924d', '136376f8-638a-4135-89f8-85d6d2df6dbd', 'Health Screening Drive', '2026-07-17', 6, 'Upcoming'),
  ('b2ac79d2-3d60-48ff-8e05-e0151df63d57', '7d3cbdc3-ae45-451e-86c5-bb70ef964beb', 'Monthly Community Dinner', '2026-05-18', 3, 'Completed'),
  ('7eb9c8d3-17b1-4f24-8b89-c5418a411c0e', '7d3cbdc3-ae45-451e-86c5-bb70ef964beb', 'Monthly Community Dinner', '2026-06-29', 3, 'Upcoming'),
  ('3e44225c-dc0b-4cf7-89f3-0316facf7ec6', '839142b6-25db-492b-8fde-0550dda637ef', 'Board Orientation Breakfast', '2026-05-27', 4, 'Completed'),
  ('691f0cd0-3ce1-49f5-8585-be6c491c71a3', '839142b6-25db-492b-8fde-0550dda637ef', 'Community Dinner', '2026-06-29', 3, 'Upcoming'),
  ('dfd7ca8c-f370-4350-8dc8-628e7a3a43e4', '3f86f7e3-7b44-4924-8956-b1fe553f1125', 'Volunteer Orientation', '2026-06-03', 2, 'Completed'),
  ('76ee65a5-3d3e-47db-84b9-af97a20c4e35', '3f86f7e3-7b44-4924-8956-b1fe553f1125', 'Summer Leadership Summit', '2026-08-01', 4, 'Upcoming'),
  ('a0249466-a49f-46a6-8758-df9b7f0f76f4', '34e1d7b6-a602-4474-8c51-da205c1e544d', 'Youth Mentorship Session', '2026-06-10', 2, 'Completed'),
  ('d9aba5ff-862e-4da3-810d-9d4659157f97', '34e1d7b6-a602-4474-8c51-da205c1e544d', 'Youth Mentorship Session', '2026-06-24', 2, 'Upcoming'),
  ('00f3eda4-9d34-4e4b-8122-d432d3da10d7', '860e7db7-163e-4dad-8fcc-f0d51f11c740', 'Spring Gala', '2026-06-12', 8, 'Completed'),
  ('6a3f1eba-1abb-4596-8636-ad49aa77789a', '860e7db7-163e-4dad-8fcc-f0d51f11c740', 'Community Dinner', '2026-06-29', 3, 'Upcoming'),
  ('ee3787d1-3039-4253-8a4b-f8f661fd75d7', '48f965a9-9ac2-4827-8fef-2c898dcd1001', 'Community Health Fair', '2026-05-27', 6, 'Completed'),
  ('5181c4f2-bfe2-4bbd-8bc7-c8842742645e', '48f965a9-9ac2-4827-8fef-2c898dcd1001', 'Health Screening Drive', '2026-07-17', 6, 'Upcoming'),
  ('d55f2e99-b0dd-4e95-884c-d460c5e42c00', '08930422-421a-4b64-8e11-61b7dfda4ceb', 'Phone Banking Session', '2026-06-07', 3, 'Completed'),
  ('2242033d-97cd-4d9e-860f-cade0ed69eb4', '08930422-421a-4b64-8e11-61b7dfda4ceb', 'Annual Fund Drive', '2026-07-07', 3, 'Upcoming'),
  ('4d5358bf-8145-45da-8614-b98d19fdc12a', '04dbeb0e-00b8-497f-8040-d3171d144a8d', 'Community Dinner', '2026-05-18', 3, 'Completed'),
  ('ab510d75-0a6f-4b7e-835e-0cf57c3c4a31', '04dbeb0e-00b8-497f-8040-d3171d144a8d', 'Community Dinner', '2026-06-29', 3, 'Upcoming'),
  ('d039170d-a76c-4f29-8c26-85d3046e513f', '3b9ef0a9-c7ec-41bd-8afc-0d61deaf9272', 'Spring Gala', '2026-06-12', 10, 'Completed'),
  ('969d18e6-019b-47b4-8a34-09d7ffe45e8e', '3b9ef0a9-c7ec-41bd-8afc-0d61deaf9272', 'Summer Leadership Summit', '2026-08-01', 8, 'Upcoming'),
  ('be25a357-ed80-4b9b-89de-1aa772031402', '21609218-a3b9-48d3-8fd4-e2641234b1df', 'Youth Mentorship Session', '2026-06-10', 2, 'Cancelled'),
  ('980d8d28-bc53-41f4-8357-f2953808ecc8', '21609218-a3b9-48d3-8fd4-e2641234b1df', 'Youth Mentorship Session', '2026-06-24', 2, 'Upcoming')
ON CONFLICT (id) DO UPDATE SET
  volunteer_id = EXCLUDED.volunteer_id,
  event_name = EXCLUDED.event_name,
  date = EXCLUDED.date,
  hours = EXCLUDED.hours,
  status = EXCLUDED.status,
  updated_at = now();
