-- ============================================================
-- SEED: Nonprofit Campaigns + Donations
-- AUTO-GENERATED by scripts/generate-nonprofit-seed.ts
-- Source: src/shared/data/nonprofitDemoData.ts
-- Safe to re-run (idempotent upserts on fixed seed UUIDs).
-- Prerequisite: at least one row in auth.users
-- ============================================================

-- Abort if no auth users (created_by subquery would be NULL)
DO $$
BEGIN
  IF (SELECT COUNT(*) FROM auth.users) = 0 THEN
    RAISE EXCEPTION 'SEED ABORTED: No users in auth.users. Sign up via the app first.';
  END IF;
END $$;


DELETE FROM public.nonprofit_donations WHERE id IN ('7a258763-251e-4889-8c8c-396fdd13eeb2', '480ad7a9-c7a8-4d12-841e-9a1b035e89cd', 'eac7653c-e636-4f18-8b65-ce914bf5178c', '7fc85a8d-52b2-443d-8e30-2f0ef65b56be', '06d30f58-2f96-4ef0-8549-cd033e4b84d2', 'e7486550-a00c-479f-8645-8eb1437dc7ad', '12d03547-a522-4405-8183-a01141a5ac4d', 'e72e875d-8782-4066-8d84-8baf0cc3bf27', 'b3a9409d-4569-4d1d-831d-8b9ab7b157d8', '3a060329-bdb0-4353-83b7-10d8011e97d6', '5f11ef22-1d28-4220-84f2-fc1929fdbe10', '2b3e6019-d9cf-4381-8d46-bb010f36a45c', 'aa905779-c48b-45ea-8bf1-688150d0067d', '613345cc-e169-435c-80bd-1265502a43e9', 'e7774689-95f5-45aa-8f35-1a34bc7956af', 'c720b8fe-2c1f-4c52-8ee7-5f5321ff0d1b', '536d5d02-735b-443d-851b-e2ff3529874d', '524ddd6e-7043-473e-8838-cef2fd78c1f3', 'a60b50d0-a921-435b-8dfc-a2151adcb3dd', 'f89fcd0f-88da-4700-88bb-73add85c96a9');
DELETE FROM public.nonprofit_campaigns WHERE id IN ('80f61bfc-83c0-41a3-8e5c-7b20dcbc99d8', '714d9071-f78c-49ed-8e9e-659cc1ece3b0', '3b7cffbc-6b0d-4282-8e2a-e33c7ec28ea6');

INSERT INTO public.nonprofit_campaigns (
  id, created_by, name, description, goal, raised, donor_count, start_date, end_date, is_active, fund_designation
) VALUES
  ('80f61bfc-83c0-41a3-8e5c-7b20dcbc99d8', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Spring Annual Fund', 'Our core operating fund that supports all Brightside programs, staff, and community services. Every dollar goes directly to our mission.', 75000, 48200, 183, '2026-04-18', '2026-07-17', TRUE, 'General Operating'),
  ('714d9071-f78c-49ed-8e9e-659cc1ece3b0', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Technology Access Initiative', 'Bridging the digital divide for underserved youth and families. Funds laptops, internet access stipends, and digital literacy training.', 25000, 18400, 67, '2026-05-03', '2026-08-01', TRUE, 'Technology Fund'),
  ('3b7cffbc-6b0d-4282-8e2a-e33c7ec28ea6', (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Youth Mentorship Endowment', 'Building a permanent endowment to sustain our youth mentorship programs in perpetuity. A legacy gift that will serve Boston''s youth for generations.', 100000, 31000, 42, '2026-03-19', NULL, TRUE, 'Youth Programs')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  goal = EXCLUDED.goal,
  raised = EXCLUDED.raised,
  donor_count = EXCLUDED.donor_count,
  start_date = EXCLUDED.start_date,
  end_date = EXCLUDED.end_date,
  is_active = EXCLUDED.is_active,
  fund_designation = EXCLUDED.fund_designation,
  updated_at = now();

INSERT INTO public.nonprofit_donations (
  id, campaign_id, donor_name, donor_email, amount, frequency, fund_designation, is_anonymous, payment_method, created_at
) VALUES
  ('7a258763-251e-4889-8c8c-396fdd13eeb2', '80f61bfc-83c0-41a3-8e5c-7b20dcbc99d8', 'Sarah Mitchell', NULL, 2500, 'Annual', 'General Operating', FALSE, 'Credit Card', '2026-06-16 12:00:00+00'),
  ('480ad7a9-c7a8-4d12-841e-9a1b035e89cd', '80f61bfc-83c0-41a3-8e5c-7b20dcbc99d8', 'Robert Kim', NULL, 500, 'Monthly', 'General Operating', FALSE, 'ACH', '2026-06-16 12:00:00+00'),
  ('eac7653c-e636-4f18-8b65-ce914bf5178c', '3b7cffbc-6b0d-4282-8e2a-e33c7ec28ea6', 'Anonymous', NULL, 1000, 'One-Time', 'Youth Programs', TRUE, 'Credit Card', '2026-06-15 12:00:00+00'),
  ('7fc85a8d-52b2-443d-8e30-2f0ef65b56be', '3b7cffbc-6b0d-4282-8e2a-e33c7ec28ea6', 'Patricia Lee', NULL, 5000, 'Annual', 'Youth Programs', FALSE, 'Check', '2026-06-14 12:00:00+00'),
  ('06d30f58-2f96-4ef0-8549-cd033e4b84d2', '80f61bfc-83c0-41a3-8e5c-7b20dcbc99d8', 'Margaret Chen', NULL, 150, 'Monthly', 'General Operating', FALSE, 'Credit Card', '2026-06-13 12:00:00+00'),
  ('e7486550-a00c-479f-8645-8eb1437dc7ad', '714d9071-f78c-49ed-8e9e-659cc1ece3b0', 'David Chen', NULL, 750, 'One-Time', 'Technology Fund', FALSE, 'PayPal', '2026-06-12 12:00:00+00'),
  ('12d03547-a522-4405-8183-a01141a5ac4d', '714d9071-f78c-49ed-8e9e-659cc1ece3b0', 'Jennifer Walsh', NULL, 250, 'Quarterly', 'Technology Fund', FALSE, 'ACH', '2026-06-10 12:00:00+00'),
  ('e72e875d-8782-4066-8d84-8baf0cc3bf27', '80f61bfc-83c0-41a3-8e5c-7b20dcbc99d8', 'Kevin Park', NULL, 1000, 'Annual', 'General Operating', FALSE, 'Check', '2026-06-09 12:00:00+00'),
  ('b3a9409d-4569-4d1d-831d-8b9ab7b157d8', '80f61bfc-83c0-41a3-8e5c-7b20dcbc99d8', 'Anonymous', NULL, 50, 'Monthly', 'General Operating', TRUE, 'Credit Card', '2026-06-08 12:00:00+00'),
  ('3a060329-bdb0-4353-83b7-10d8011e97d6', '3b7cffbc-6b0d-4282-8e2a-e33c7ec28ea6', 'Thomas Rivera', NULL, 300, 'One-Time', 'Youth Programs', FALSE, 'Credit Card', '2026-06-07 12:00:00+00'),
  ('5f11ef22-1d28-4220-84f2-fc1929fdbe10', '714d9071-f78c-49ed-8e9e-659cc1ece3b0', 'Dr. Alicia Ramos', NULL, 200, 'Monthly', 'Technology Fund', FALSE, 'ACH', '2026-06-05 12:00:00+00'),
  ('2b3e6019-d9cf-4381-8d46-bb010f36a45c', '3b7cffbc-6b0d-4282-8e2a-e33c7ec28ea6', 'Lisa Chen', NULL, 10000, 'Annual', 'Youth Programs', FALSE, 'Check', '2026-06-03 12:00:00+00'),
  ('aa905779-c48b-45ea-8bf1-688150d0067d', '80f61bfc-83c0-41a3-8e5c-7b20dcbc99d8', 'Carol Nguyen', NULL, 75, 'Monthly', 'General Operating', FALSE, 'Credit Card', '2026-06-02 12:00:00+00'),
  ('613345cc-e169-435c-80bd-1265502a43e9', '80f61bfc-83c0-41a3-8e5c-7b20dcbc99d8', 'Marcus Webb', NULL, 500, 'One-Time', 'General Operating', FALSE, 'PayPal', '2026-05-31 12:00:00+00'),
  ('e7774689-95f5-45aa-8f35-1a34bc7956af', '714d9071-f78c-49ed-8e9e-659cc1ece3b0', 'Priya Mehta', NULL, 1500, 'Annual', 'Technology Fund', FALSE, 'ACH', '2026-05-28 12:00:00+00'),
  ('c720b8fe-2c1f-4c52-8ee7-5f5321ff0d1b', '80f61bfc-83c0-41a3-8e5c-7b20dcbc99d8', 'Anonymous', NULL, 25, 'Monthly', 'General Operating', TRUE, 'Credit Card', '2026-05-26 12:00:00+00'),
  ('536d5d02-735b-443d-851b-e2ff3529874d', '3b7cffbc-6b0d-4282-8e2a-e33c7ec28ea6', 'Angela Torres', NULL, 400, 'Quarterly', 'Youth Programs', FALSE, 'Credit Card', '2026-05-23 12:00:00+00'),
  ('524ddd6e-7043-473e-8838-cef2fd78c1f3', '3b7cffbc-6b0d-4282-8e2a-e33c7ec28ea6', 'James Wright', NULL, 2000, 'Annual', 'Youth Programs', FALSE, 'Check', '2026-05-18 12:00:00+00'),
  ('a60b50d0-a921-435b-8dfc-a2151adcb3dd', '80f61bfc-83c0-41a3-8e5c-7b20dcbc99d8', 'Robert Okafor', NULL, 100, 'Monthly', 'General Operating', FALSE, 'ACH', '2026-05-13 12:00:00+00'),
  ('f89fcd0f-88da-4700-88bb-73add85c96a9', '714d9071-f78c-49ed-8e9e-659cc1ece3b0', 'Susan Park', NULL, 600, 'One-Time', 'Technology Fund', FALSE, 'Credit Card', '2026-05-03 12:00:00+00')
ON CONFLICT (id) DO UPDATE SET
  campaign_id = EXCLUDED.campaign_id,
  donor_name = EXCLUDED.donor_name,
  amount = EXCLUDED.amount,
  frequency = EXCLUDED.frequency,
  fund_designation = EXCLUDED.fund_designation,
  is_anonymous = EXCLUDED.is_anonymous,
  payment_method = EXCLUDED.payment_method,
  created_at = EXCLUDED.created_at,
  updated_at = now();
