#!/usr/bin/env bash
# Concatenate all timestamped migration files into one SQL bootstrap (Lovable SQL Editor).
# Use: npm run migrations:concat

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MIGRATIONS_DIR="$PROJECT_ROOT/supabase/migrations"
OUTPUT="$PROJECT_ROOT/supabase/bootstrap-all-migrations.sql"

cd "$PROJECT_ROOT"

{
  echo "-- Auto-generated by scripts/concat-migrations.sh — do not edit manually."
  echo "-- Re-run: npm run migrations:concat"
  echo "-- Apply in Supabase SQL Editor or: npm run migrations:run (with DATABASE_URL in .env)"
  echo "-- Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo ""
  echo "BEGIN;"
  echo ""

  # Timestamped migrations in lexicographic order (matches Supabase CLI ordering).
  for f in "$MIGRATIONS_DIR"/[0-9]*_*.sql; do
    [ -f "$f" ] || continue
    echo "-- ============================================================================="
    echo "-- $(basename "$f")"
    echo "-- ============================================================================="
    cat "$f"
    echo ""
    echo ""
  done

  # Optional manual fix-up (not tracked by supabase migration history).
  if [ -f "$MIGRATIONS_DIR/RUN_IF_admin_exec_sql_MISSING.sql" ]; then
    echo "-- ============================================================================="
    echo "-- RUN_IF_admin_exec_sql_MISSING.sql (optional)"
    echo "-- ============================================================================="
    cat "$MIGRATIONS_DIR/RUN_IF_admin_exec_sql_MISSING.sql"
    echo ""
  fi

  echo "COMMIT;"
} > "$OUTPUT"

count=$(find "$MIGRATIONS_DIR" -maxdepth 1 -name '[0-9]*_*.sql' | wc -l | tr -d ' ')
bytes=$(wc -c < "$OUTPUT" | tr -d ' ')

echo "Wrote $OUTPUT"
echo "  Migrations: $count files"
echo "  Size:       $bytes bytes"
